# Generated by Django 2.0.6 on 2018-11-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
