# Generated by Django 2.0.6 on 2018-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181124_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='ticket_number',
        ),
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.CharField(default='OPEN', max_length=50),
        ),
    ]
