# Generated by Django 2.0.6 on 2018-11-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181125_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=50)),
                ('validUpto', models.DateField()),
                ('savedAs', models.CharField(max_length=150)),
                ('bankName', models.CharField(max_length=200)),
                ('cardType', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
