# Generated by Django 2.0.6 on 2018-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_savedcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcards',
            name='validUpto',
        ),
        migrations.AddField(
            model_name='savedcards',
            name='validMonth',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='savedcards',
            name='validYear',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='savedcards',
            name='bankName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='savedcards',
            name='cardNumber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedcards',
            name='cardType',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedcards',
            name='nameOnCard',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='savedcards',
            name='savedAs',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
