# Generated by Django 2.0.6 on 2018-11-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedCards',
            new_name='SavedCard',
        ),
    ]
