# Generated by Django 2.0.6 on 2018-11-28 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181127_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Reminder', max_length=1024)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('alarms', models.CharField(max_length=1024)),
                ('repeat', models.CharField(choices=[(('DA',), 'Daily'), ('SD', 'Selected Day(s) Of Week'), ('ID', 'In Interval of Days')], default=('DA',), max_length=100)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('intervalGap', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('daysOfWeek', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
