# Generated by Django 2.0.6 on 2018-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181129_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='repeat',
            field=models.CharField(choices=[(('DA',), 'Daily'), ('SD', 'Selected Day(s) Of Week'), ('ID', 'In Interval of Days')], default='DA', max_length=2),
        ),
    ]
