# Generated by Django 2.0.6 on 2018-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181201_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
