# Generated by Django 2.0.6 on 2018-11-24 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20181124_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='review',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='rating',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='hospital',
            field=models.ForeignKey(default=1, help_text='Hospital List', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='icon_file',
            field=models.ImageField(help_text='Select Additional Service Icon', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(help_text='Enter Additional Serviec Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='value',
            field=models.CharField(help_text='Some Value for the Additional Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True, help_text='Visibility Symbol'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Enter the Department Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=1, help_text='Select the practive of the doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=1, help_text='Enter Doctor Experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=3, help_text='Hospital Name', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(help_text='Enter the doctor name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time_slot',
            field=models.CharField(blank=True, help_text='Visiting Time Slots', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='about',
            field=models.TextField(blank=True, help_text='Enter the details of the about', max_length=20480, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='departments',
            field=models.ManyToManyField(help_text='Include the list of the departments for the Event', to='hospital.Department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_file',
            field=models.FileField(blank=True, help_text='Event Related File', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='hospital',
            field=models.ForeignKey(default=1, help_text='Hospital Name', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_file',
            field=models.ImageField(help_text='Select Image File for the Event', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Enter the title for the Event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(help_text='Feedback Message to hospital', max_length=20480),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='seen',
            field=models.BooleanField(default=False, help_text='This indicates that feedback has been seen by hospital'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='to',
            field=models.ForeignKey(default=3, help_text='Hospital to which feedback has been send', on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=2, help_text='Sender Details of the Feedback', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='about',
            field=models.TextField(blank=True, help_text='Enter about the hospital', max_length=20480, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='active',
            field=models.BooleanField(default=True, help_text='Validated Hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, help_text='Enter Full Adress of Hospital', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='api_key',
            field=models.CharField(blank=True, help_text='Validation/Subscription Key for the hospital', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the current City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, help_text='Enter the current District', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload the Hospital Name', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.CharField(blank=True, help_text='Geo coordinates of the Hospital', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the Name of the Hospital', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, help_text='Hospital Contact Number List', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.CharField(blank=True, help_text='Enter the Pincode', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='start_date',
            field=models.DateField(blank=True, help_text='Subscription Start Date', null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date of Change Done'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='valid_date',
            field=models.DateField(blank=True, help_text='Subscription End Date', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='category',
            field=models.CharField(blank=True, default='Select Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='hr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='name',
            field=models.CharField(help_text='HR Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='hr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image_file',
            field=models.ImageField(blank=True, help_text='select jpg or png only.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.TextField(help_text='Enter the comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1, help_text='Select Rating out of 5'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='recommended',
            field=models.BooleanField(default=True, help_text='Select Recommendation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True, help_text='Activation Symbol'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent_nonac',
            field=models.FloatField(blank=True, help_text='Non Ac Rent', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, help_text='Visibility Symbol'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(default=0, help_text='Enter the cost of service without implant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_implant',
            field=models.FloatField(default=0, help_text='Enter the cost of service with implant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.ForeignKey(default=1, help_text='Department List', on_delete=django.db.models.deletion.CASCADE, to='hospital.Department'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Enter the Service Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated Date'),
        ),
    ]
